version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - redis
    env_file: .env.docker
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clothing_store
    expose:
      - 5432
  redis:
    image: redis
    restart: on-failure
    expose:
      - 6379
